<a href="https://colab.research.google.com/github/Nilanjan1210/PyTorch-Fundamentals/blob/main/01.Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch is a Python-based scientific computing package serving two broad purposes:

* A replacement for NumPy to use the power of GPUs and other accelerators.

* An automatic differentiation library that is useful to implement neural networks.

## **What are Tensors?**

Tensor holds a multi-dimensional array of elements of a single data type which is very similar with numpy’s ndarray. When the dimension is zero, it can be called a scalar. When the dimension is 1, it can be called a vector. When the dimension is 2, it can be called a matrix.

- 0-dimensional tensor: A single number (scalar).
- 1-dimensional tensor: A list of numbers (vector).
- 2-dimensional tensor: A table of numbers (matrix).

When the dimension is greater than 2, it is usually called a tensor.

In [ ]:
import torch
import numpy as np
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Print versions
print("torch version:", torch.__version__)
print("numpy version:", np.__version__)

torch version: 2.6.0+cu124
numpy version: 2.0.2


In [ ]:
# Creating a tensor
# using empty method
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [ ]:
type(x)

torch.Tensor

In [ ]:
x.dtype

torch.float32

## Tensor Initialization

In [ ]:
# Directly from data
data = [[7,8],[3,5]]
x = torch.tensor(data)
print(x)

tensor([[7, 8],
        [3, 5]])


In [ ]:
# usign zeros
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# using ones
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# using rand
x = torch.rand(2,3)
print(x)

tensor([[0.7200, 0.4621, 0.6482],
        [0.6012, 0.5924, 0.5865]])


In [ ]:
# to regenarate same random number to fixed seed
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
# using tesor fuction
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# using arrange fucntion
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
# using linspace
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [ ]:
# usign eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
# using full
torch.full((2,3),4)

tensor([[4, 4, 4],
        [4, 4, 4]])

In [ ]:
# to check tensor shape
z = torch.rand(2,3)
z.shape

torch.Size([2, 3])

In [ ]:
# Usign empty fucntion to create a same shape tansor
print(torch.empty_like(z))
print(torch.zeros_like(z))
print(torch.ones_like(z))

tensor([[0.0000e+00, 0.0000e+00, 1.8788e+31],
        [1.7220e+22, 2.1715e-18, 2.6705e+23]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# Create a tensor with values drawn from a normal distribution
x = torch.empty(1, 5).normal_(mean=0, std=1)
print("Normal Distributed Tensor:\n", x)

Normal Distributed Tensor:
 tensor([[ 2.2082, -0.6380,  0.4617,  0.2674,  0.5349]])


In [ ]:
# Create a tensor with values drawn from a uniform distribution
x = torch.empty(1, 5).uniform_(0, 1)
print("Uniform Distributed Tensor:\n", x)

Uniform Distributed Tensor:
 tensor([[0.1053, 0.2695, 0.3588, 0.1994, 0.5472]])


In [ ]:
# Create a diagonal tensor from a tensor of ones
x = torch.diag(torch.ones(4))
print("Diagonal Tensor:\n", x)

Diagonal Tensor:
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


## Tensor Type Conversion

In [ ]:
# when we create tensor to assign data type
x = torch.tensor([1,2,3,34], dtype=torch.float)
print(x)

tensor([ 1.,  2.,  3., 34.])


In [ ]:
x.dtype

torch.float32

In [ ]:
x = torch.tensor([1,2,3,34], dtype=torch.int64)
print(x)

tensor([ 1,  2,  3, 34])


In [ ]:
x.dtype

torch.int64

In [ ]:
# Create a tensor and convert its type
tensor = torch.arange(4)
print("Boolean Tensor:", tensor.bool())   # Convert to boolean
print("Short Tensor (int16):", tensor.short())   # Convert to int16
print("Long Tensor (int64):", tensor.long())   # Convert to int64
print("Half Tensor (float16):", tensor.half())   # Convert to float16
print("Float Tensor (float32):", tensor.float())   # Convert to float32
print("Double Tensor (float64):", tensor.double())   # Convert to float64

Boolean Tensor: tensor([False,  True,  True,  True])
Short Tensor (int16): tensor([0, 1, 2, 3], dtype=torch.int16)
Long Tensor (int64): tensor([0, 1, 2, 3])
Half Tensor (float16): tensor([0., 1., 2., 3.], dtype=torch.float16)
Float Tensor (float32): tensor([0., 1., 2., 3.])
Double Tensor (float64): tensor([0., 1., 2., 3.], dtype=torch.float64)


## Tensor Mathematics and Comparison Operations

In [ ]:
# Mathematical Operation
x = torch.tensor(range(1,10), dtype=float).reshape(3,3)
y = torch.tensor(range(9,0,-1), dtype=float).reshape(3,3)
print(x)
print(y)
print(x+2)
print(x-2)
print(x*2)
print(x/2)
print(x%2)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)



tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)
tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]], dtype=torch.float64)
tensor([[ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.],
        [ 5.,  6.,  7.]], dtype=torch.float64)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]], dtype=torch.float64)
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000],
        [3.5000, 4.0000, 4.5000]], dtype=torch.float64)
tensor([[1., 0., 1.],
        [0., 1., 0.],
        [1., 0., 1.]], dtype=torch.float64)
tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]], dtype=torch.float64)
tensor([[-8., -6., -4.],
        [-2.,  0.,  2.],
        [ 4.,  6.,  8.]], dtype=torch.float64)
tensor([[ 9., 16., 21.],
        [24., 25., 24.],
        [21., 16.,  9.]], dtype=torch.float64)
tensor([[0.1111, 0.2500, 0.428

In [ ]:
c = torch.tensor([1,-2,3,-4]  ,dtype  = float)
print(torch.abs(c))

tensor([1., 2., 3., 4.], dtype=torch.float64)


In [ ]:
torch.neg(c)

tensor([-1.,  2., -3.,  4.], dtype=torch.float64)

In [ ]:
torch.manual_seed(123)
d  = torch.rand(3,4)
print(d )
print(torch.round(d))
print(torch.ceil(d))
print(torch.floor(d))
print(torch.trunc(d))
print(torch.frac(d)) # fractional part is the remainder after dividing the number by 1.

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])
tensor([[0., 1., 0., 1.],
        [0., 1., 0., 0.],
        [0., 1., 0., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])


In [ ]:
torch.manual_seed(12)
d  = torch.rand(3,4)
print(d )
print(d.max())
print(d.max(dim=0)) # sum of along column
print(d.max(dim=1)) # sum of along row
print(d.min())
print(d.min(dim=0))
print(d.min(dim=1))
print(d.mean)
print(d.mean(dim=0))
print(d.mean(dim=1))
print(d.sum())
print(d.sum(dim=0))
print(d.sum(dim=1))
print(d.std())
print(d.std(dim=0))
print(d.std(dim=1))

tensor([[0.4657, 0.2328, 0.4527, 0.5871],
        [0.4086, 0.1272, 0.6373, 0.2421],
        [0.7312, 0.7224, 0.1992, 0.6948]])
tensor(0.7312)
torch.return_types.max(
values=tensor([0.7312, 0.7224, 0.6373, 0.6948]),
indices=tensor([2, 2, 1, 2]))
torch.return_types.max(
values=tensor([0.5871, 0.6373, 0.7312]),
indices=tensor([3, 2, 0]))
tensor(0.1272)
torch.return_types.min(
values=tensor([0.4086, 0.1272, 0.1992, 0.2421]),
indices=tensor([1, 1, 2, 1]))
torch.return_types.min(
values=tensor([0.2328, 0.1272, 0.1992]),
indices=tensor([1, 1, 2]))
<built-in method mean of Tensor object at 0x78ce6e88a1b0>
tensor([0.5352, 0.3608, 0.4297, 0.5080])
tensor([0.4346, 0.3538, 0.5869])
tensor(5.5011)
tensor([1.6055, 1.0824, 1.2892, 1.5240])
tensor([1.7383, 1.4152, 2.3477])
tensor(0.2186)
tensor([0.1721, 0.3176, 0.2199, 0.2365])
tensor([0.1475, 0.2215, 0.2589])


In [ ]:
torch.manual_seed(101)
d  = torch.rand(3,4)
print(d )
# Clamp method
print(torch.clamp(d,min=0.2,max=0.8))

tensor([[0.1980, 0.4503, 0.0909, 0.8872],
        [0.2894, 0.0186, 0.9095, 0.3406],
        [0.4309, 0.7324, 0.4776, 0.0716]])
tensor([[0.2000, 0.4503, 0.2000, 0.8000],
        [0.2894, 0.2000, 0.8000, 0.3406],
        [0.4309, 0.7324, 0.4776, 0.2000]])


In [ ]:
print(torch.median(d))
print(torch.median(d,dim=0) )
print(torch.median(d,dim=1))

tensor(0.3406)
torch.return_types.median(
values=tensor([0.2894, 0.4503, 0.4776, 0.3406]),
indices=tensor([1, 0, 2, 1]))
torch.return_types.median(
values=tensor([0.1980, 0.2894, 0.4309]),
indices=tensor([0, 0, 0]))


In [ ]:
print(torch.prod(d))
print(torch.prod(d,dim=0))
print(torch.prod(d,dim=1))

tensor(1.2940e-07)
tensor([0.0247, 0.0061, 0.0395, 0.0216])
tensor([0.0072, 0.0017, 0.0108])


In [ ]:
#  Stander deviation
print(torch.std(d))
print(torch.var(d))
print(d)
print(torch.argmax(d))
print(torch.argmin(d))

tensor(0.3047)
tensor(0.0929)
tensor([[0.1980, 0.4503, 0.0909, 0.8872],
        [0.2894, 0.0186, 0.9095, 0.3406],
        [0.4309, 0.7324, 0.4776, 0.0716]])
tensor(6)
tensor(5)


In [ ]:
# Matrix operation or 2D tensor operation
f = torch.randint(size=(2,3), low = 0, high = 20)
g = torch.randint(size=(3,2), low = 0, high = 20)
print(f)
print(g)
# matrix miltiplictaion
print(torch.mm(f,g))
print(torch.matmul(f,g))
print(torch.transpose(f,0,1))

tensor([[ 0, 15, 12],
        [17, 12,  0]])
tensor([[ 8, 18],
        [ 1, 16],
        [ 9, 12]])
tensor([[123, 384],
        [148, 498]])
tensor([[123, 384],
        [148, 498]])
tensor([[ 0, 17],
        [15, 12],
        [12,  0]])


In [ ]:
h = torch.randint(size=(3,3), low = 0, high = 20,
dtype = float)
print(h)
print(torch.det(h))

tensor([[17., 15., 11.],
        [ 2., 16., 11.],
        [ 9.,  3.,  7.]], dtype=torch.float64)
tensor(1100.0000, dtype=torch.float64)


### Implace operator

In [ ]:
# Implace operator
# we want to change and store in same variable the use methosname_ like "add_" method
m = torch.randint(size=(2,3), low = 0, high = 20)
print(m)
m.add_(10)
print(m)

tensor([[ 6, 16, 16],
        [17, 11, 14]])
tensor([[16, 26, 26],
        [27, 21, 24]])


In [ ]:
# Copy a tencor
a = torch.randint(size=(2,3), low = 0, high = 20)
c = a
print(id(a))
print(id(c))
print(a)
b = a.clone()
print(b)
print(id(b))

132824174437744
132824174437744
tensor([[18,  8, 11],
        [11,  3,  8]])
tensor([[18,  8, 11],
        [11,  3,  8]])
132824174434768


## Tensor operation on GPU

In [ ]:
# TO ENABEL YOUR GPU
print(torch.cuda.is_available())
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
print(torch.cuda.is_available())

True
cuda
True


In [ ]:
# creating a new tensor in GPU
torch.rand((2,3), device=device)

tensor([[0.6941, 0.0714, 0.3151],
        [0.0764, 0.6683, 0.1244]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a = torch.rand((2,3))
b = a.to(device)
print(b+5) # to perform on GPU


tensor([[5.8646, 5.2945, 5.6296],
        [5.8637, 5.4373, 5.5454]], device='cuda:0')


In [ ]:
# To check the performance on GPU
import  torch
import time
size = 10000
#Create random matrix on CPU
matrix_cpu1 = torch.rand((size,size))
matrix_cpu2 = torch.rand((size,size))
# measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
end_time = time.time()
print("Time taken on CPU:", end_time - start_time)
#Create random matrix on GPU
matrix_gpu1 = matrix_cpu1.to("cuda")
matrix_gpu2 = matrix_cpu2.to("cuda")
start_time = time.time()
# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
end_time = time.time()
print("Time taken on GPU:", end_time - start_time)


Time taken on CPU: 26.012566089630127
Time taken on GPU: 0.12827014923095703


### Reshaping Tensor

Learn how to reshape tensors, concatenate them, and change the order of dimensions.

- **Reshape with `view()` & `reshape()`:** Change tensor shape without altering data.  
- **Transpose & Flatten:** `.t()` transposes, `.contiguous().view(-1)` flattens.  
- **Concatenation:** `torch.cat([x1, x2], dim=0/1)` merges tensors along rows/columns.  
- **Flattening:** `.view(-1)` converts a tensor into a 1D array.  
- **Batch Reshaping:** `.view(batch, -1)` keeps batch size while reshaping.  
- **Permute Dimensions:** `.permute(0, 2, 1)` reorders dimensions efficiently.  
- **Unsqueeze for New Dimensions:** `.unsqueeze(dim)` adds singleton dimensions.  

In [ ]:
# Reshape a tensor using view and reshape
x = torch.arange(9)
x_3x3 = x.view(3, 3)
print("Reshaped to 3x3 using view:\n", x_3x3)
x_3x3 = x.reshape(3, 3)
print("Reshaped to 3x3 using reshape:\n", x_3x3)

# Transpose and flatten the tensor
y = x_3x3.t()
print("Flattened transposed tensor:", y.contiguous().view(9))

# Concatenation example
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)
print("Concatenated along dimension 0 (rows):", torch.cat([x1, x2], dim=0).shape)
print("Concatenated along dimension 1 (columns):", torch.cat([x1, x2], dim=1).shape)

# Flatten the tensor using view(-1)
z = x1.view(-1)
print("Flattened tensor shape:", z.shape)

# Reshape with batch dimension
batch = 64
x = torch.rand(batch, 2, 5)
print("Reshaped to (batch, -1):", x.view(batch, -1).shape)

# Permute dimensions
z = x.permute(0, 2, 1)
print("Permuted tensor shape:", z.shape)

# Unsqueeze examples (adding new dimensions)
x = torch.arange(10)
print("Original x:", x)
print("x unsqueezed at dim 0:", x.unsqueeze(0).shape, x.unsqueeze(0))
print("x unsqueezed at dim 1:", x.unsqueeze(1).shape, x.unsqueeze(1))



Reshaped to 3x3 using view:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Reshaped to 3x3 using reshape:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Flattened transposed tensor: tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
Concatenated along dimension 0 (rows): torch.Size([4, 5])
Concatenated along dimension 1 (columns): torch.Size([2, 10])
Flattened tensor shape: torch.Size([10])
Reshaped to (batch, -1): torch.Size([64, 10])
Permuted tensor shape: torch.Size([64, 5, 2])
Original x: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x unsqueezed at dim 0: torch.Size([1, 10]) tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
x unsqueezed at dim 1: torch.Size([10, 1]) tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [ ]:
# flater
a.flatten()

tensor([0.8646, 0.2945, 0.6296, 0.8637, 0.4373, 0.5454])

In [ ]:
# permute
b = torch.rand((2,3,4))
print(b.permute(2,0,1))
print(b.permute(2,0,1).shape)

tensor([[[0.7551, 0.4140, 0.9094],
         [0.7420, 0.8681, 0.0143]],

        [[0.0997, 0.8477, 0.8745],
         [0.7777, 0.6427, 0.5511]],

        [[0.4784, 0.4345, 0.7340],
         [0.3145, 0.2296, 0.4671]],

        [[0.9117, 0.9657, 0.5313],
         [0.3740, 0.7941, 0.3918]]])
torch.Size([4, 2, 3])


In [ ]:
# unsqueeze
# Adding a dimension to given position
a = torch.rand((225,225,3))
print(a.unsqueeze(0).shape)
print(a.unsqueeze(1).shape)

torch.Size([1, 225, 225, 3])
torch.Size([225, 1, 225, 3])


In [ ]:
# squeeze
# remove a dimesion to given position
a = torch.rand((20,3))
print(a.squeeze(0).shape)
print(a.squeeze(1))
print(a.squeeze(0).shape)

torch.Size([20, 3])
tensor([[0.2684, 0.5794, 0.2507],
        [0.3332, 0.7685, 0.6920],
        [0.7884, 0.7881, 0.1183],
        [0.5608, 0.5378, 0.3610],
        [0.7564, 0.8695, 0.8760],
        [0.6970, 0.4151, 0.1832],
        [0.5837, 0.9292, 0.6023],
        [0.1765, 0.8409, 0.2726],
        [0.4108, 0.4721, 0.5486],
        [0.4303, 0.5698, 0.0138],
        [0.0624, 0.2059, 0.2380],
        [0.4575, 0.7061, 0.5698],
        [0.6979, 0.6558, 0.0333],
        [0.2058, 0.5423, 0.5916],
        [0.5919, 0.4311, 0.7392],
        [0.9544, 0.9235, 0.6654],
        [0.6221, 0.8454, 0.8856],
        [0.5157, 0.0368, 0.0961],
        [0.4858, 0.7852, 0.4251],
        [0.0601, 0.8568, 0.7990]])
torch.Size([20, 3])


In [ ]:
# Numpy to PyTorch
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(torch.from_numpy(a))
print(type(a))
print(type(torch.from_numpy(a)))

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


## Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

### Tensor to NumPy array

In [ ]:
# Tensor to NumPy array


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [ ]:
# NumPy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
