<a href="https://colab.research.google.com/github/Nilanjan1210/PyTorch-Fundamentals/blob/main/03_Pytorch_Neural_Networksipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Neural networks can be constructed using the torch.nn package.

It is a simple feed-forward network. It takes the input, feeds it through several layers one after the other, and then finally gives the output.

A typical training procedure for a neural network is as follows:

* Define the neural network that has some learnable parameters (or weights)

* Iterate over a dataset of inputs

* Process input through the network

* Compute the loss (how far is the output from being correct)

* Propagate gradients back into the network’s parameters

* Update the weights of the network, typically using a simple update rule:
```
weight = weight - learning_rate * gradient
```



In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
# create model class
class NNModel(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out



In [3]:
# Create Dataset
features = torch.rand(10,5)

# create model
model = NNModel(features.shape[1])

# print model
print(model)

NNModel(
  (linear): Linear(in_features=5, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


In [4]:
# forward pass
output = model(features)
print(output)

tensor([[0.2469],
        [0.2559],
        [0.2936],
        [0.3168],
        [0.3214],
        [0.3202],
        [0.2678],
        [0.2735],
        [0.2978],
        [0.2387]], grad_fn=<SigmoidBackward0>)


In [5]:
# to show model weights
model.linear.weight

Parameter containing:
tensor([[-0.2557, -0.4199, -0.0849, -0.4213, -0.2127]], requires_grad=True)

In [6]:
# to show model bias
model.linear.bias

Parameter containing:
tensor([-0.2365], requires_grad=True)

In [9]:
! pip install torchinfo

In [10]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
NNModel                                  [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [11]:
class NNModel1(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    # self.linear1 = nn.Linear(num_features, 3)
    # self.relu = nn.ReLU()
    # self.linear2 = nn.Linear(3, 1)
    # self.sigmoid = nn.Sigmoid()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    # out = self.linear1(features)
    # out = self.relu(out)
    # out = self.linear2(out)
    # out = self.sigmoid(out)
    out = self.network(features)
    return out

In [12]:
# create model
model = NNModel1(features.shape[1])

# print model
print(model)

NNModel1(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)


In [13]:
# forward pass
output = model(features)
print(output)

tensor([[0.4338],
        [0.4273],
        [0.4262],
        [0.4254],
        [0.4123],
        [0.4343],
        [0.4254],
        [0.4116],
        [0.4254],
        [0.4321]], grad_fn=<SigmoidBackward0>)


In [14]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
NNModel1                                 [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00